image: docker

stages:
  - test
  - build
  - deploy

variables:
  CONTAINER_IMAGE: codenetix/laravel-dms-backend:$CI_BUILD_REF_NAME
  PLATFORM_IMAGE: codenetix/laravel-dms-backend-platform:latest

test:
  stage: test
  image:
    name: $PLATFORM_IMAGE
  services:
    - mysql:5.7.22
  variables:
    MYSQL_DATABASE: dms_test
    MYSQL_ROOT_PASSWORD: dms
    APP_ENV: test
    DB_DATABASE: dms_test
    DB_HOST: mysql
    DB_PASSWORD: dms
    DB_USERNAME: root
    APP_KEY: '"base64:N5A11hYX5GxzTqEPRtoRHjtdtqg65hGpw2Qis1V4b8M="'
    GIT_STRATEGY: clone
  script:
    - composer install
    - vendor/bin/phpcs --standard=phpcs.xml --runtime-set ignore_warnings_on_exit true
    - vendor/bin/phpunit tests/Feature -c phpunit.xml --coverage-text --colors=never
  tags:
    - docker-build

build:
  stage: build
  script:
    - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD
    - docker build --pull -t $CONTAINER_IMAGE .
    - docker push $CONTAINER_IMAGE
  only:
    - dev
    - master
  tags:
    - docker-build

deploy_dev:
  image: codenetix/kubectl
  variables:
    GIT_STRATEGY: none
  stage: deploy
  only:
    - dev
  script:
    - kubectl set env deploy/dms-backend-deployment DEPLOY_DATE="$(date)" -n dms-dev
  tags:
    - docker-build
