version: '3'

services:
  backend_app:
    image: codenetix/laravel-dms-backend:dev
    container_name: dms_backend_app
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        - ENABLE_OPCACHE=false
        - INSTALL_XDEBUG=true
    environment:
      APP_ENV: local
      APP_DEBUG: 'true'
      APP_KEY: '"base64:N5A11hYX5GxzTqEPRtoRHjtdtqg65hGpw2Qis1V4b8M="'
      DB_DATABASE: dms
      DB_HOST: mysql
      DB_PASSWORD: dms
      DB_USERNAME: root
      XDEBUG_CONFIG: 'remote_host=192.168.88.109 remote_connect_back=0 idekey=PHPSTORM'
    networks:
      - backend
    volumes:
      - ./:/var/www/
    ports:
      - 80:80/tcp

  mysql:
    image: mysql:5.7.22
    container_name: mysql
    environment:
      MYSQL_DATABASE: dms
      MYSQL_ROOT_PASSWORD: dms
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - 3306:3306/tcp
    networks:
      - backend

  app_php_unit:
    image: codenetix/laravel-dms-backend
    container_name: dms_app_php_unit
    environment:
      APP_ENV: local
      APP_DEBUG: 'true'
      APP_KEY: '"base64:N5A11hYX5GxzTqEPRtoRHjtdtqg65hGpw2Qis1V4b8M="'
      DB_DATABASE: dms
      DB_HOST: mysql
      DB_PASSWORD: dms
      DB_USERNAME: root
      XDEBUG_CONFIG: 'remote_host=192.168.88.109 remote_connect_back=0 idekey=PHPSTORM'
    volumes:
      - ./:/var/www/
    networks:
      - backend

volumes:
  mysql-data:
  schema:

networks:
  backend:
    driver: bridge