version: '3'

services:
  backend-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dms-backend-app
    environment:
      APP_ENV: prod
      APP_DEBUG: 'false'
      APP_KEY: '"base64:N5A11hYX5GxzTqEPRtoRHjtdtqg65hGpw2Qis1V4b8M="'
      DB_DATABASE: dms
      DB_HOST: mysql
      DB_PASSWORD: dms
      DB_USERNAME: root
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7.22
    container_name: dms-mysql
    environment:
      MYSQL_DATABASE: dms
      MYSQL_ROOT_PASSWORD: dms
    volumes:
      - mysql-data:/var/lib/mysql:cached
    ports:
      - 3306:3306/tcp

volumes:
  mysql-data:
  schema: