version: '3'

services:
  backend-app:
    image: codenetix/laravel-dms-backend:dev
    container_name: dms-backend-app
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        - ENABLE_OPCACHE=false
        - INSTALL_XDEBUG=false
    environment:
      APP_ENV: local
      APP_DEBUG: 'true'
      APP_KEY: '"base64:N5A11hYX5GxzTqEPRtoRHjtdtqg65hGpw2Qis1V4b8M="'
      DB_DATABASE: dms
      DB_HOST: mysql
      DB_PASSWORD: dms
      DB_USERNAME: root
      XDEBUG_CONFIG: 'remote_host=${LOCAL_IP} remote_connect_back=0 idekey=PHPSTORM'
    networks:
      - backend
    volumes:
#      - ./app:/var/www/app
#      - ./tests:/var/www/tests
#      - ./config:/var/www/config
#      - ./database:/var/www/database
#      - ./resources:/var/www/resources
#      - ./routes:/var/www/routes
      - ./:/var/www:cached

  mysql:
    image: mysql:5.7.22
    container_name: mysql
    environment:
      MYSQL_DATABASE: dms
      MYSQL_ROOT_PASSWORD: dms
    volumes:
      - mysql-data:/var/lib/mysql:cached
    ports:
      - 3306:3306/tcp
    networks:
      - backend

  app-php-unit:
    image: codenetix/laravel-dms-backend
    container_name: dms-app-php-unit
    environment:
      APP_ENV: local
      APP_DEBUG: 'true'
      APP_KEY: '"base64:N5A11hYX5GxzTqEPRtoRHjtdtqg65hGpw2Qis1V4b8M="'
      DB_DATABASE: dms
      DB_HOST: mysql
      DB_PASSWORD: dms
      DB_USERNAME: root
      XDEBUG_CONFIG: 'remote_host=192.168.88.109 remote_connect_back=0 idekey=PHPSTORM'
    volumes:
      - ./app:/var/www/app
      - ./tests:/var/www/tests
      - ./config:/var/www/config
      - ./database:/var/www/database
      - ./resources:/var/www/resources
      - ./routes:/var/www/routes
    networks:
      - backend

volumes:
  mysql-data:
  schema:

networks:
  backend:
    driver: bridge