version: '3'

services:
  app:
    image: dms_app
    container_name: dms_app
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      APP_ENV: local
      APP_DEBUG: 'true'
      APP_KEY: '"base64:N5A11hYX5GxzTqEPRtoRHjtdtqg65hGpw2Qis1V4b8M="'
      DB_DATABASE: dms
      DB_HOST: mysql
      DB_PASSWORD: dms
      DB_USERNAME: root
      XDEBUG_CONFIG: remote_host=192.168.0.106
      XDEBUG_REMOTE_HOST: 192.168.0.106
    volumes:
      - ./:/var/www
    links:
      - mysql:mysql
    ports:
      - 80:80/tcp
#      - 9000:9000
    restart: "always"
  mysql:
    image: mysql:latest
    container_name: dms_mysql
    environment:
      MYSQL_DATABASE: dms
      MYSQL_ROOT_PASSWORD: dms
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - 3306:3306/tcp
    restart: "always"
  validation-generator:
    image: registry.codenetix.com/documentation/laravel-validation-generator:master
    volumes:
      - ./config/validation.json:/generator/out.json
      - /Users/barmotinvladimir/Tree-Soft-Projects/dms/api-specification:/schema
  schema:
    image: registry.codenetix.com/dms/api-specification:master
    volumes:
      - schema:/schema

  mysql_test:
    image: mysql:latest
    container_name: dms_mysql_test
    environment:
      MYSQL_DATABASE: dms_test
      MYSQL_ROOT_PASSWORD: dms
  app_test:
    image: dms_app
    container_name: dms_app_test
    environment:
      APP_ENV: test
      APP_DEBUG: 'false'
      APP_KEY: '"base64:N5A11hYX5GxzTqEPRtoRHjtdtqg65hGpw2Qis1V4b8M="'
      DB_DATABASE: dms_test
      DB_HOST: mysql_test
      DB_PASSWORD: dms
      DB_USERNAME: root

    links:
      - mysql_test:mysql_test
    command: 'php artisan migrate'

  testing_api:
    image: registry.codenetix.com/documentation/testing:master
    links:
      - app_test:dms_app
    environment:
      - TESTING_URI=http://dms_app/v1
    volumes:
      - schema:/schema

volumes:
  mysql-data:
  schema: